~[\]()=^$|]+$/.test(selectorToCheck))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+selector);if(!goog.html.SafeStyleSheet.hasBalancedBrackets_(selectorToCheck))throw Error("() and [] in selector must be balanced, got: "+
selector);style instanceof goog.html.SafeStyle||(style=goog.html.SafeStyle.create(style));var styleSheet=selector+"{"+goog.html.SafeStyle.unwrap(style).replace(/</g,"\\3C ")+"}";return goog.html.SafeStyleSheet.createSafeStyleSheetSecurityPrivateDoNotAccessOrElse(styleSheet)};
goog.html.SafeStyleSheet.hasBalancedBrackets_=function(s){for(var brackets={"(":")","[":"]"},expectedBrackets=[],i=0;i<s.length;i++){var ch=s[i];if(brackets[ch])expectedBrackets.push(brackets[ch]);else if(goog.object.contains(brackets,ch)&&expectedBrackets.pop()!=ch)return!1}return 0==expectedBrackets.length};
goog.html.SafeStyleSheet.concat=function(var_args){var result="",addArgument=function(argument){goog.isArray(argument)?goog.array.forEach(argument,addArgument):result+=goog.html.SafeStyleSheet.unwrap(argument)};goog.array.forEach(arguments,addArgument);return goog.html.SafeStyleSheet.createSafeStyleSheetSecurityPrivateDoNotAccessOrElse(result)};
goog.html.SafeStyleSheet.fromConstant=function(styleSheet){var styleSheetString=goog.string.Const.unwrap(styleSheet);if(0===styleSheetString.length)return goog.html.SafeStyleSheet.EMPTY;goog.asserts.assert(!goog.string.internal.contains(styleSheetString,"<"),"Forbidden '<' character in style sheet string: "+styleSheetString);return goog.html.SafeStyleSheet.createSafeStyleSheetSecurityPrivateDoNotAccessOrElse(styleSheetString)};goog.html.SafeStyleSheet.prototype.getTypedStringValue=function(){return this.privateDoNotAccessOrElseSafeStyleSheetWrappedValue_};
goog.DEBUG&&(goog.html.SafeStyleSheet.prototype.toString=function(){return"SafeStyleSheet{"+this.privateDoNotAccessOrElseSafeStyleSheetWrappedValue_+"}"});
goog.html.SafeStyleSheet.unwrap=function(safeStyleSheet){if(safeStyleSheet instanceof goog.html.SafeStyleSheet&&safeStyleSheet.constructor===goog.html.SafeStyleSheet&&safeStyleSheet.SAFE_STYLE_SHEET_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_===goog.html.SafeStyleSheet.TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_)return safeStyleSheet.privateDoNotAccessOrElseSafeStyleSheetWrappedValue_;goog.asserts.fail("expected object of type SafeStyleSheet, got '"+safeStyleSheet+"' of type "+goog.typeOf(safeStyleSheet));
return"type_error:SafeStyleSheet"};goog.html.SafeStyleSheet.createSafeStyleSheetSecurityPrivateDoNotAccessOrElse=function(styleSheet){return(new goog.html.SafeStyleSheet).initSecurityPrivateDoNotAccessOrElse_(styleSheet)};goog.html.SafeStyleSheet.prototype.initSecurityPrivateDoNotAccessOrElse_=function(styleSheet){this.privateDoNotAccessOrElseSafeStyleSheetWrappedValue_=styleSheet;return this};goog.html.SafeStyleSheet.EMPTY=goog.html.SafeStyleSheet.createSafeStyleSheetSecurityPrivateDoNotAccessOrElse("");goog.labs={};goog.labs.userAgent={};goog.labs.userAgent.util={};goog.labs.userAgent.util.getNativeUserAgentString_=function(){var navigator=goog.labs.userAgent.util.getNavigator_();if(navigator){var userAgent=navigator.userAgent;if(userAgent)return userAgent}return""};goog.labs.userAgent.util.getNavigator_=function(){return goog.global.navigator};goog.labs.userAgent.util.userAgent_=goog.labs.userAgent.util.getNativeUserAgentString_();
goog.labs.userAgent.util.setUserAgent=function(opt_userAgent){goog.labs.userAgent.util.userAgent_=opt_userAgent||goog.labs.userAgent.util.getNativeUserAgentString_()};goog.labs.userAgent.util.getUserAgent=function(){return goog.labs.userAgent.util.userAgent_};goog.labs.userAgent.util.matchUserAgent=function(str){var userAgent=goog.labs.userAgent.util.getUserAgent();return goog.string.internal.contains(userAgent,str)};
goog.labs.userAgent.util.matchUserAgentIgnoreCase=function(str){var userAgent=goog.labs.userAgent.util.getUserAgent();return goog.string.internal.caseInsensitiveContains(userAgent,str)};goog.labs.userAgent.util.extractVersionTuples=function(userAgent){for(var versionRegExp=/(\w[\w ]+)\/([^\s]+)\s*(?:\((.*?)\))?/g,data=[],match;match=versionRegExp.exec(userAgent);)data.push([match[1],match[2],match[3]||void 0]);return data};goog.labs.userAgent.browser={};goog.labs.userAgent.browser.matchOpera_=function(){return goog.labs.userAgent.util.matchUserAgent("Opera")};goog.labs.userAgent.browser.matchIE_=function(){return goog.labs.userAgent.util.matchUserAgent("Trident")||goog.labs.userAgent.util.matchUserAgent("MSIE")};goog.labs.userAgent.browser.matchEdgeHtml_=function(){return goog.labs.userAgent.util.matchUserAgent("Edge")};goog.labs.userAgent.browser.matchEdgeChromium_=function(){return goog.labs.userAgent.util.matchUserAgent("Edg/")};
goog.labs.userAgent.browser.matchOperaChromium_=function(){return goog.labs.userAgent.util.matchUserAgent("OPR")};goog.labs.userAgent.browser.matchFirefox_=function(){return goog.labs.userAgent.util.matchUserAgent("Firefox")||goog.labs.userAgent.util.matchUserAgent("FxiOS")};
goog.labs.userAgent.browser.matchSafari_=function(){return goog.labs.userAgent.util.matchUserAgent("Safari")&&!(goog.labs.userAgent.browser.matchChrome_()||goog.labs.userAgent.browser.matchCoast_()||goog.labs.userAgent.browser.matchOpera_()||goog.labs.userAgent.browser.matchEdgeHtml_()||goog.labs.userAgent.browser.matchEdgeChromium_()||goog.labs.userAgent.browser.matchOperaChromium_()||goog.labs.userAgent.browser.matchFirefox_()||goog.labs.userAgent.browser.isSilk()||goog.labs.userAgent.util.matchUserAgent("Android"))};
goog.labs.userAgent.browser.matchCoast_=function(){return goog.labs.userAgent.util.matchUserAgent("Coast")};goog.labs.userAgent.browser.matchIosWebview_=function(){return(goog.labs.userAgent.util.matchUserAgent("iPad")||goog.labs.userAgent.util.matchUserAgent("iPhone"))&&!goog.labs.userAgent.browser.matchSafari_()&&!goog.labs.userAgent.browser.matchChrome_()&&!goog.labs.userAgent.browser.matchCoast_()&&!goog.labs.userAgent.browser.matchFirefox_()&&goog.labs.userAgent.util.matchUserAgent("AppleWebKit")};
goog.labs.userAgent.browser.matchChrome_=function(){return(goog.labs.userAgent.util.matchUserAgent("Chrome")||goog.labs.userAgent.util.matchUserAgent("CriOS"))&&!goog.labs.userAgent.browser.matchEdgeHtml_()};goog.labs.userAgent.browser.matchAndroidBrowser_=function(){return goog.labs.userAgent.util.matchUserAgent("Android")&&!(goog.labs.userAgent.browser.isChrome()||goog.labs.userAgent.browser.isFirefox()||goog.labs.userAgent.browser.isOpera()||goog.labs.userAgent.browser.isSilk())};
goog.labs.userAgent.browser.isOpera=goog.labs.userAgent.browser.matchOpera_;goog.labs.userAgent.browser.isIE=goog.labs.userAgent.browser.matchIE_;goog.labs.userAgent.browser.isEdge=goog.labs.userAgent.browser.matchEdgeHtml_;goog.labs.userAgent.browser.isEdgeChromium=goog.labs.userAgent.browser.matchEdgeChromium_;goog.labs.userAgent.browser.isOperaChromium=goog.labs.userAgent.browser.matchOperaChromium_;goog.labs.userAgent.browser.isFirefox=goog.labs.userAgent.browser.matchFirefox_;
goog.labs.userAgent.browser.isSafari=goog.labs.userAgent.browser.matchSafari_;goog.labs.userAgent.browser.isCoast=goog.labs.userAgent.browser.matchCoast_;goog.labs.userAgent.browser.isIosWebview=goog.labs.userAgent.browser.matchIosWebview_;goog.labs.userAgent.browser.isChrome=goog.labs.userAgent.browser.matchChrome_;goog.labs.userAgent.browser.isAndroidBrowser=goog.labs.userAgent.browser.matchAndroidBrowser_;goog.labs.userAgent.browser.isSilk=function(){return goog.labs.userAgent.util.matchUserAgent("Silk")};
goog.labs.userAgent.browser.getVersion=function(){function lookUpValueWithKeys(keys){var key=goog.array.find(keys,versionMapHasKey);return versionMap[key]||""}var userAgentString=goog.labs.userAgent.util.getUserAgent();if(goog.labs.userAgent.browser.isIE())return goog.labs.userAgent.browser.getIEVersion_(userAgentString);var versionTuples=goog.labs.userAgent.util.extractVersionTuples(userAgentString),versionMap={};goog.array.forEach(versionTuples,function(tuple){var key=tuple[0],value=tuple[1];versionMap[key]=
value});var versionMapHasKey=goog.partial(goog.object.containsKey,versionMap);if(goog.labs.userAgent.browser.isOpera())return lookUpValueWithKeys(["Version","Opera"]);if(goog.labs.userAgent.browser.isEdge())return lookUpValueWithKeys(["Edge"]);if(goog.labs.userAgent.browser.isEdgeChromium())return lookUpValueWithKeys(["Edg"]);if(goog.labs.userAgent.browser.isChrome())return lookUpValueWithKeys(["Chrome","CriOS"]);var tuple=versionTuples[2];return tuple&&tuple[1]||""};
goog.labs.userAgent.browser.isVersionOrHigher=function(version){return 0<=goog.string.internal.compareVersions(goog.labs.userAgent.browser.getVersion(),version)};
goog.labs.userAgent.browser.getIEVersion_=function(userAgent){var rv=/rv: *([\d\.]*)/.exec(userAgent);if(rv&&rv[1])return rv[1];var version="",msie=/MSIE +([\d\.]+)/.exec(userAgent);if(msie&&msie[1]){var tridentVersion=/Trident\/(\d.\d)/.exec(userAgent);if("7.0"==msie[1])if(tridentVersion&&tridentVersion[1])switch(tridentVersion[1]){case "4.0":version="8.0";break;case "5.0":version="9.0";break;case "6.0":version="10.0";break;case "7.0":version="11.0"}else version="7.0";else version=msie[1]}return version};goog.html.SafeHtml=function(){this.privateDoNotAccessOrElseSafeHtmlWrappedValue_="";this.SAFE_HTML_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_=goog.html.SafeHtml.TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_;this.dir_=null};goog.html.SafeHtml.ENABLE_ERROR_MESSAGES=goog.DEBUG;goog.html.SafeHtml.SUPPORT_STYLE_ATTRIBUTE=!0;goog.html.SafeHtml.prototype.implementsGoogI18nBidiDirectionalString=!0;goog.html.SafeHtml.prototype.getDirection=function(){return this.dir_};
goog.html.SafeHtml.prototype.implementsGoogStringTypedString=!0;goog.html.SafeHtml.prototype.getTypedStringValue=function(){return this.privateDoNotAccessOrElseSafeHtmlWrappedValue_.toString()};goog.DEBUG&&(goog.html.SafeHtml.prototype.toString=function(){return"SafeHtml{"+this.privateDoNotAccessOrElseSafeHtmlWrappedValue_+"}"});goog.html.SafeHtml.unwrap=function(safeHtml){return goog.html.SafeHtml.unwrapTrustedHTML(safeHtml).toString()};
goog.html.SafeHtml.unwrapTrustedHTML=function(safeHtml){if(safeHtml instanceof goog.html.SafeHtml&&safeHtml.constructor===goog.html.SafeHtml&&safeHtml.SAFE_HTML_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_===goog.html.SafeHtml.TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_)return safeHtml.privateDoNotAccessOrElseSafeHtmlWrappedValue_;goog.asserts.fail("expected object of type SafeHtml, got '"+safeHtml+"' of type "+goog.typeOf(safeHtml));return"type_error:SafeHtml"};
goog.html.SafeHtml.htmlEscape=function(textOrHtml){if(textOrHtml instanceof goog.html.SafeHtml)return textOrHtml;var textIsObject="object"==typeof textOrHtml,dir=null;textIsObject&&textOrHtml.implementsGoogI18nBidiDirectionalString&&(dir=textOrHtml.getDirection());var textAsString=textIsObject&&textOrHtml.implementsGoogStringTypedString?textOrHtml.getTypedStringValue():String(textOrHtml);return goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(goog.string.internal.htmlEscape(textAsString),
dir)};goog.html.SafeHtml.htmlEscapePreservingNewlines=function(textOrHtml){if(textOrHtml instanceof goog.html.SafeHtml)return textOrHtml;var html=goog.html.SafeHtml.htmlEscape(textOrHtml);return goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(goog.string.internal.newLineToBr(goog.html.SafeHtml.unwrap(html)),html.getDirection())};
goog.html.SafeHtml.htmlEscapePreservingNewlinesAndSpaces=function(textOrHtml){if(textOrHtml instanceof goog.html.SafeHtml)return textOrHtml;var html=goog.html.SafeHtml.htmlEscape(textOrHtml);return goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(goog.string.internal.whitespaceEscape(goog.html.SafeHtml.unwrap(html)),html.getDirection())};goog.html.SafeHtml.from=goog.html.SafeHtml.htmlEscape;goog.html.SafeHtml.VALID_NAMES_IN_TAG_=/^[a-zA-Z0-9-]+$/;
goog.html.SafeHtml.URL_ATTRIBUTES_={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};goog.html.SafeHtml.NOT_ALLOWED_TAG_NAMES_={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};goog.html.SafeHtml.create=function(tagName,opt_attributes,opt_content){goog.html.SafeHtml.verifyTagName(String(tagName));return goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse(String(tagName),opt_attributes,opt_content)};
goog.html.SafeHtml.verifyTagName=function(tagName){if(!goog.html.SafeHtml.VALID_NAMES_IN_TAG_.test(tagName))throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?"Invalid tag name <"+tagName+">.":"");if(tagName.toUpperCase()in goog.html.SafeHtml.NOT_ALLOWED_TAG_NAMES_)throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?"Tag name <"+tagName+"> is not allowed for SafeHtml.":"");};
goog.html.SafeHtml.createIframe=function(opt_src,opt_srcdoc,opt_attributes,opt_content){opt_src&&goog.html.TrustedResourceUrl.unwrap(opt_src);var fixedAttributes={};fixedAttributes.src=opt_src||null;fixedAttributes.srcdoc=opt_srcdoc&&goog.html.SafeHtml.unwrap(opt_srcdoc);var defaultAttributes={sandbox:""},attributes=goog.html.SafeHtml.combineAttributes(fixedAttributes,defaultAttributes,opt_attributes);return goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse("iframe",attributes,
opt_content)};
goog.html.SafeHtml.createSandboxIframe=function(opt_src,opt_srcdoc,opt_attributes,opt_content){if(!goog.html.SafeHtml.canUseSandboxIframe())throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?"The browser does not support sandboxed iframes.":"");var fixedAttributes={};fixedAttributes.src=opt_src?goog.html.SafeUrl.unwrap(goog.html.SafeUrl.sanitize(opt_src)):null;fixedAttributes.srcdoc=opt_srcdoc||null;fixedAttributes.sandbox="";var attributes=goog.html.SafeHtml.combineAttributes(fixedAttributes,{},
opt_attributes);return goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse("iframe",attributes,opt_content)};goog.html.SafeHtml.canUseSandboxIframe=function(){return goog.global.HTMLIFrameElement&&"sandbox"in goog.global.HTMLIFrameElement.prototype};
goog.html.SafeHtml.createScriptSrc=function(src,opt_attributes){goog.html.TrustedResourceUrl.unwrap(src);var fixedAttributes={src:src},defaultAttributes={},attributes=goog.html.SafeHtml.combineAttributes(fixedAttributes,defaultAttributes,opt_attributes);return goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse("script",attributes)};
goog.html.SafeHtml.createScript=function(script,opt_attributes){for(var attr in opt_attributes){var attrLower=attr.toLowerCase();if("language"==attrLower||"src"==attrLower||"text"==attrLower||"type"==attrLower)throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?'Cannot set "'+attrLower+'" attribute':"");}var content="";script=goog.array.concat(script);for(var i=0;i<script.length;i++)content+=goog.html.SafeScript.unwrap(script[i]);var htmlContent=goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(content,
goog.i18n.bidi.Dir.NEUTRAL);return goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse("script",opt_attributes,htmlContent)};
goog.html.SafeHtml.createStyle=function(styleSheet,opt_attributes){var fixedAttributes={type:"text/css"},defaultAttributes={},attributes=goog.html.SafeHtml.combineAttributes(fixedAttributes,defaultAttributes,opt_attributes),content="";styleSheet=goog.array.concat(styleSheet);for(var i=0;i<styleSheet.length;i++)content+=goog.html.SafeStyleSheet.unwrap(styleSheet[i]);var htmlContent=goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(content,goog.i18n.bidi.Dir.NEUTRAL);return goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse("style",
attributes,htmlContent)};
goog.html.SafeHtml.createMetaRefresh=function(url,opt_secs){var unwrappedUrl=goog.html.SafeUrl.unwrap(goog.html.SafeUrl.sanitize(url));(goog.labs.userAgent.browser.isIE()||goog.labs.userAgent.browser.isEdge())&&goog.string.internal.contains(unwrappedUrl,";")&&(unwrappedUrl="'"+unwrappedUrl.replace(/'/g,"%27")+"'");var attributes={"http-equiv":"refresh",content:(opt_secs||0)+"; url="+unwrappedUrl};return goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse("meta",attributes)};
goog.html.SafeHtml.getAttrNameAndValue_=function(tagName,name,value){if(value instanceof goog.string.Const)value=goog.string.Const.unwrap(value);else if("style"==name.toLowerCase())if(goog.html.SafeHtml.SUPPORT_STYLE_ATTRIBUTE)value=goog.html.SafeHtml.getStyleValue_(value);else throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?'Attribute "style" not supported.':"");else{if(/^on/i.test(name))throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?'Attribute "'+name+'" requires goog.string.Const value, "'+
value+'" given.':"");if(name.toLowerCase()in goog.html.SafeHtml.URL_ATTRIBUTES_)if(value instanceof goog.html.TrustedResourceUrl)value=goog.html.TrustedResourceUrl.unwrap(value);else if(value instanceof goog.html.SafeUrl)value=goog.html.SafeUrl.unwrap(value);else if("string"===typeof value)value=goog.html.SafeUrl.sanitize(value).getTypedStringValue();else throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?'Attribute "'+name+'" on tag "'+tagName+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+
value+'" given.':"");}value.implementsGoogStringTypedString&&(value=value.getTypedStringValue());goog.asserts.assert("string"===typeof value||"number"===typeof value,"String or number value expected, got "+typeof value+" with value: "+value);return name+'="'+goog.string.internal.htmlEscape(String(value))+'"'};
goog.html.SafeHtml.getStyleValue_=function(value){if(!goog.isObject(value))throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?'The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof value+" given: "+value:"");value instanceof goog.html.SafeStyle||(value=goog.html.SafeStyle.create(value));return goog.html.SafeStyle.unwrap(value)};
goog.html.SafeHtml.createWithDir=function(dir,tagName,opt_attributes,opt_content){var html=goog.html.SafeHtml.create(tagName,opt_attributes,opt_content);html.dir_=dir;return html};
goog.html.SafeHtml.join=function(separator,parts){var separatorHtml=goog.html.SafeHtml.htmlEscape(separator),dir=separatorHtml.getDirection(),content=[],addArgument=function(argument){if(goog.isArray(argument))goog.array.forEach(argument,addArgument);else{var html=goog.html.SafeHtml.htmlEscape(argument);content.push(goog.html.SafeHtml.unwrap(html));var htmlDir=html.getDirection();dir==goog.i18n.bidi.Dir.NEUTRAL?dir=htmlDir:htmlDir!=goog.i18n.bidi.Dir.NEUTRAL&&dir!=htmlDir&&(dir=null)}};goog.array.forEach(parts,
addArgument);return goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(content.join(goog.html.SafeHtml.unwrap(separatorHtml)),dir)};goog.html.SafeHtml.concat=function(var_args){return goog.html.SafeHtml.join(goog.html.SafeHtml.EMPTY,Array.prototype.slice.call(arguments))};goog.html.SafeHtml.concatWithDir=function(dir,var_args){var html=goog.html.SafeHtml.concat(goog.array.slice(arguments,1));html.dir_=dir;return html};goog.html.SafeHtml.TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_={};
goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse=function(html,dir){return(new goog.html.SafeHtml).initSecurityPrivateDoNotAccessOrElse_(html,dir)};goog.html.SafeHtml.prototype.initSecurityPrivateDoNotAccessOrElse_=function(html,dir){this.privateDoNotAccessOrElseSafeHtmlWrappedValue_=goog.html.trustedtypes.PRIVATE_DO_NOT_ACCESS_OR_ELSE_POLICY?goog.html.trustedtypes.PRIVATE_DO_NOT_ACCESS_OR_ELSE_POLICY.createHTML(html):html;this.dir_=dir;return this};
goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse=function(tagName,opt_attributes,opt_content){var dir=null,result="<"+tagName;result+=goog.html.SafeHtml.stringifyAttributes(tagName,opt_attributes);var content=opt_content;null==content?content=[]:goog.isArray(content)||(content=[content]);if(goog.dom.tags.isVoidTag(tagName.toLowerCase()))goog.asserts.assert(!content.length,"Void tag <"+tagName+"> does not allow content."),result+=">";else{var html=goog.html.SafeHtml.concat(content);
result+=">"+goog.html.SafeHtml.unwrap(html)+"</"+tagName+">";dir=html.getDirection()}var dirAttribute=opt_attributes&&opt_attributes.dir;dirAttribute&&(dir=/^(ltr|rtl|auto)$/i.test(dirAttribute)?goog.i18n.bidi.Dir.NEUTRAL:null);return goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(result,dir)};
goog.html.SafeHtml.stringifyAttributes=function(tagName,opt_attributes){var result="";if(opt_attributes)for(var name in opt_attributes){if(!goog.html.SafeHtml.VALID_NAMES_IN_TAG_.test(name))throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?'Invalid attribute name "'+name+'".':"");var value=opt_attributes[name];null!=value&&(result+=" "+goog.html.SafeHtml.getAttrNameAndValue_(tagName,name,value))}return result};
goog.html.SafeHtml.combineAttributes=function(fixedAttributes,defaultAttributes,opt_attributes){var combinedAttributes={},name;for(name in fixedAttributes)goog.asserts.assert(name.toLowerCase()==name,"Must be lower case"),combinedAttributes[name]=fixedAttributes[name];for(name in defaultAttributes)goog.asserts.assert(name.toLowerCase()==name,"Must be lower case"),combinedAttributes[name]=defaultAttributes[name];if(opt_attributes)for(name in opt_attributes){var nameLower=name.toLowerCase();if(nameLower in
fixedAttributes)throw Error(goog.html.SafeHtml.ENABLE_ERROR_MESSAGES?'Cannot override "'+nameLower+'" attribute, got "'+name+'" with value "'+opt_attributes[name]+'"':"");nameLower in defaultAttributes&&delete combinedAttributes[nameLower];combinedAttributes[name]=opt_attributes[name]}return combinedAttributes};goog.html.SafeHtml.DOCTYPE_HTML=goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse("<!DOCTYPE html>",goog.i18n.bidi.Dir.NEUTRAL);
goog.html.SafeHtml.EMPTY=goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse("",goog.i18n.bidi.Dir.NEUTRAL);goog.html.SafeHtml.BR=goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse("<br>",goog.i18n.bidi.Dir.NEUTRAL);goog.html.uncheckedconversions={};goog.html.uncheckedconversions.safeHtmlFromStringKnownToSatisfyTypeContract=function(justification,html,opt_dir){goog.asserts.assertString(goog.string.Const.unwrap(justification),"must provide justification");goog.asserts.assert(!goog.string.internal.isEmptyOrWhitespace(goog.string.Const.unwrap(justification)),"must provide non-empty justification");return goog.html.SafeHtml.createSafeHtmlSecurityPrivateDoNotAccessOrElse(html,opt_dir||null)};
goog.html.uncheckedconversions.safeScriptFromStringKnownToSatisfyTypeContract=function(justification,script){goog.asserts.assertString(goog.string.Const.unwrap(justification),"must provide justification");goog.asserts.assert(!goog.string.internal.isEmptyOrWhitespace(goog.string.Const.unwrap(justification)),"must provide non-empty justification");return goog.html.SafeScript.createSafeScriptSecurityPrivateDoNotAccessOrElse(script)};
goog.html.uncheckedconversions.safeStyleFromStringKnownToSatisfyTypeContract=function(justification,style){goog.asserts.assertString(goog.string.Const.unwrap(justification),"must provide justification");goog.asserts.assert(!goog.string.internal.isEmptyOrWhitespace(goog.string.Const.unwrap(justification)),"must provide non-empty justification");return goog.html.SafeStyle.createSafeStyleSecurityPrivateDoNotAccessOrElse(style)};
goog.html.uncheckedconversions.safeStyleSheetFromStringKnownToSatisfyTypeContract=function(justification,styleSheet){goog.asserts.assertString(goog.string.Const.unwrap(justification),"must provide justification");goog.asserts.assert(!goog.string.internal.isEmptyOrWhitespace(goog.string.Const.unwrap(justification)),"must provide non-empty justification");return goog.html.SafeStyleSheet.createSafeStyleSheetSecurityPrivateDoNotAccessOrElse(styleSheet)};
goog.html.uncheckedconversions.safeUrlFromStringKnownToSatisfyTypeContract=function(justification,url){goog.asserts.assertString(goog.string.Const.unwrap(justification),"must provide justification");goog.asserts.assert(!goog.string.internal.isEmptyOrWhitespace(goog.string.Const.unwrap(justification)),"must provide non-empty justification");return goog.html.SafeUrl.createSafeUrlSecurityPrivateDoNotAccessOrElse(url)};
goog.html.uncheckedconversions.trustedResourceUrlFromStringKnownToSatisfyTypeContract=function(justification,url){goog.asserts.assertString(goog.string.Const.unwrap(justification),"must provide justification");goog.asserts.assert(!goog.string.internal.isEmptyOrWhitespace(goog.string.Const.unwrap(justification)),"must provide non-empty justification");return goog.html.TrustedResourceUrl.createTrustedResourceUrlSecurityPrivateDoNotAccessOrElse(url)};goog.dom.safe={};goog.dom.safe.InsertAdjacentHtmlPosition={AFTERBEGIN:"afterbegin",AFTEREND:"afterend",BEFOREBEGIN:"beforebegin",BEFOREEND:"beforeend"};goog.dom.safe.insertAdjacentHtml=function(node,position,html){node.insertAdjacentHTML(position,goog.html.SafeHtml.unwrapTrustedHTML(html))};goog.dom.safe.SET_INNER_HTML_DISALLOWED_TAGS_={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};
goog.dom.safe.isInnerHtmlCleanupRecursive_=goog.functions.cacheReturnValue(function(){if(goog.DEBUG&&"undefined"===typeof document)return!1;var div=document.createElement("div"),childDiv=document.createElement("div");childDiv.appendChild(document.createElement("div"));div.appendChild(childDiv);if(goog.DEBUG&&!div.firstChild)return!1;var innerChild=div.firstChild.firstChild;div.innerHTML=goog.html.SafeHtml.unwrapTrustedHTML(goog.html.SafeHtml.EMPTY);return!innerChild.parentElement});
goog.dom.safe.unsafeSetInnerHtmlDoNotUseOrElse=function(elem,html){if(goog.dom.safe.isInnerHtmlCleanupRecursive_())for(;elem.lastChild;)elem.removeChild(elem.lastChild);elem.innerHTML=goog.html.SafeHtml.unwrapTrustedHTML(html)};
goog.dom.safe.setInnerHtml=function(elem,html){if(goog.asserts.ENABLE_ASSERTS){var tagName=elem.tagName.toUpperCase();if(goog.dom.safe.SET_INNER_HTML_DISALLOWED_TAGS_[tagName])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+elem.tagName+".");}goog.dom.safe.unsafeSetInnerHtmlDoNotUseOrElse(elem,html)};goog.dom.safe.setOuterHtml=function(elem,html){elem.outerHTML=goog.html.SafeHtml.unwrapTrustedHTML(html)};
goog.dom.safe.setFormElementAction=function(form,url){var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);goog.dom.asserts.assertIsHTMLFormElement(form).action=goog.html.SafeUrl.unwrap(safeUrl)};goog.dom.safe.setButtonFormAction=function(button,url){var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);goog.dom.asserts.assertIsHTMLButtonElement(button).formAction=goog.html.SafeUrl.unwrap(safeUrl)};
goog.dom.safe.setInputFormAction=function(input,url){var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);goog.dom.asserts.assertIsHTMLInputElement(input).formAction=goog.html.SafeUrl.unwrap(safeUrl)};goog.dom.safe.setStyle=function(elem,style){elem.style.cssText=goog.html.SafeStyle.unwrap(style)};goog.dom.safe.documentWrite=function(doc,html){doc.write(goog.html.SafeHtml.unwrapTrustedHTML(html))};
goog.dom.safe.setAnchorHref=function(anchor,url){goog.dom.asserts.assertIsHTMLAnchorElement(anchor);var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);anchor.href=goog.html.SafeUrl.unwrap(safeUrl)};
goog.dom.safe.setImageSrc=function(imageElement,url){goog.dom.asserts.assertIsHTMLImageElement(imageElement);if(url instanceof goog.html.SafeUrl)var safeUrl=url;else{var allowDataUrl=/^data:image\//i.test(url);safeUrl=goog.html.SafeUrl.sanitizeAssertUnchanged(url,allowDataUrl)}imageElement.src=goog.html.SafeUrl.unwrap(safeUrl)};
goog.dom.safe.setAudioSrc=function(audioElement,url){goog.dom.asserts.assertIsHTMLAudioElement(audioElement);if(url instanceof goog.html.SafeUrl)var safeUrl=url;else{var allowDataUrl=/^data:audio\//i.test(url);safeUrl=goog.html.SafeUrl.sanitizeAssertUnchanged(url,allowDataUrl)}audioElement.src=goog.html.SafeUrl.unwrap(safeUrl)};
goog.dom.safe.setVideoSrc=function(videoElement,url){goog.dom.asserts.assertIsHTMLVideoElement(videoElement);if(url instanceof goog.html.SafeUrl)var safeUrl=url;else{var allowDataUrl=/^data:video\//i.test(url);safeUrl=goog.html.SafeUrl.sanitizeAssertUnchanged(url,allowDataUrl)}videoElement.src=goog.html.SafeUrl.unwrap(safeUrl)};goog.dom.safe.setEmbedSrc=function(embed,url){goog.dom.asserts.assertIsHTMLEmbedElement(embed);embed.src=goog.html.TrustedResourceUrl.unwrapTrustedScriptURL(url)};
goog.dom.safe.setFrameSrc=function(frame,url){goog.dom.asserts.assertIsHTMLFrameElement(frame);frame.src=goog.html.TrustedResourceUrl.unwrap(url)};goog.dom.safe.setIframeSrc=function(iframe,url){goog.dom.asserts.assertIsHTMLIFrameElement(iframe);iframe.src=goog.html.TrustedResourceUrl.unwrap(url)};goog.dom.safe.setIframeSrcdoc=function(iframe,html){goog.dom.asserts.assertIsHTMLIFrameElement(iframe);iframe.srcdoc=goog.html.SafeHtml.unwrapTrustedHTML(html)};
goog.dom.safe.setLinkHrefAndRel=function(link,url,rel){goog.dom.asserts.assertIsHTMLLinkElement(link);link.rel=rel;goog.string.internal.caseInsensitiveContains(rel,"stylesheet")?(goog.asserts.assert(url instanceof goog.html.TrustedResourceUrl,'URL must be TrustedResourceUrl because "rel" contains "stylesheet"'),link.href=goog.html.TrustedResourceUrl.unwrap(url)):link.href=url instanceof goog.html.TrustedResourceUrl?goog.html.TrustedResourceUrl.unwrap(url):url instanceof goog.html.SafeUrl?goog.html.SafeUrl.unwrap(url):
goog.html.SafeUrl.unwrap(goog.html.SafeUrl.sanitizeAssertUnchanged(url))};goog.dom.safe.setObjectData=function(object,url){goog.dom.asserts.assertIsHTMLObjectElement(object);object.data=goog.html.TrustedResourceUrl.unwrapTrustedScriptURL(url)};goog.dom.safe.setScriptSrc=function(script,url){goog.dom.asserts.assertIsHTMLScriptElement(script);script.src=goog.html.TrustedResourceUrl.unwrapTrustedScriptURL(url);var nonce=goog.getScriptNonce();nonce&&script.setAttribute("nonce",nonce)};
goog.dom.safe.setScriptContent=function(script,content){goog.dom.asserts.assertIsHTMLScriptElement(script);script.text=goog.html.SafeScript.unwrapTrustedScript(content);var nonce=goog.getScriptNonce();nonce&&script.setAttribute("nonce",nonce)};goog.dom.safe.setLocationHref=function(loc,url){goog.dom.asserts.assertIsLocation(loc);var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);loc.href=goog.html.SafeUrl.unwrap(safeUrl)};
goog.dom.safe.assignLocation=function(loc,url){goog.dom.asserts.assertIsLocation(loc);var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);loc.assign(goog.html.SafeUrl.unwrap(safeUrl))};goog.dom.safe.replaceLocation=function(loc,url){goog.dom.asserts.assertIsLocation(loc);var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);loc.replace(goog.html.SafeUrl.unwrap(safeUrl))};
goog.dom.safe.openInWindow=function(url,opt_openerWin,opt_name,opt_specs,opt_replace){var safeUrl=url instanceof goog.html.SafeUrl?url:goog.html.SafeUrl.sanitizeAssertUnchanged(url);var win=opt_openerWin||goog.global;return win.open(goog.html.SafeUrl.unwrap(safeUrl),opt_name?goog.string.Const.unwrap(opt_name):"",opt_specs,opt_replace)};goog.dom.safe.parseFromStringHtml=function(parser,html){return goog.dom.safe.parseFromString(parser,html,"text/html")};
goog.dom.safe.parseFromString=function(parser,content,type){return parser.parseFromString(goog.html.SafeHtml.unwrapTrustedHTML(content),type)};
goog.dom.safe.createImageFromBlob=function(blob){if(!/^image\/.*/g.test(blob.type))throw Error("goog.dom.safe.createImageFromBlob only accepts MIME type image/.*.");var objectUrl=goog.global.URL.createObjectURL(blob),image=new goog.global.Image;image.onload=function(){goog.global.URL.revokeObjectURL(objectUrl)};goog.dom.safe.setImageSrc(image,goog.html.uncheckedconversions.safeUrlFromStringKnownToSatisfyTypeContract(goog.string.Const.from("Image blob URL."),objectUrl));return image};goog.string.DETECT_DOUBLE_ESCAPING=!1;goog.string.FORCE_NON_DOM_HTML_UNESCAPING=!1;goog.string.Unicode={NBSP:"\u00a0"};goog.string.startsWith=goog.string.internal.startsWith;goog.string.endsWith=goog.string.internal.endsWith;goog.string.caseInsensitiveStartsWith=goog.string.internal.caseInsensitiveStartsWith;goog.string.caseInsensitiveEndsWith=goog.string.internal.caseInsensitiveEndsWith;goog.string.caseInsensitiveEquals=goog.string.internal.caseInsensitiveEquals;
goog.string.subs=function(str,var_args){for(var splitParts=str.split("%s"),returnString="",subsArguments=Array.prototype.slice.call(arguments,1);subsArguments.length&&1<splitParts.length;)returnString+=splitParts.shift()+subsArguments.shift();return returnString+splitParts.join("%s")};goog.string.collapseWhitespace=function(str){return str.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};goog.string.isEmptyOrWhitespace=goog.string.internal.isEmptyOrWhitespace;
goog.string.isEmptyString=function(str){return 0==str.length};goog.string.isEmpty=goog.string.isEmptyOrWhitespace;goog.string.isEmptyOrWhitespaceSafe=function(str){return goog.string.isEmptyOrWhitespace(goog.string.makeSafe(str))};goog.string.isEmptySafe=goog.string.isEmptyOrWhitespaceSafe;goog.string.isBreakingWhitespace=function(str){return!/[^\t\n\r ]/.test(str)};goog.string.isAlpha=function(str){return!/[^a-zA-Z]/.test(str)};goog.string.isNumeric=function(str){return!/[^0-9]/.test(str)};
goog.string.isAlphaNumeric=function(str){return!/[^a-zA-Z0-9]/.test(str)};goog.string.isSpace=function(ch){return" "==ch};goog.string.isUnicodeChar=function(ch){return 1==ch.length&&" "<=ch&&"~">=ch||"\u0080"<=ch&&"\ufffd">=ch};goog.string.stripNewlines=function(str){return str.replace(/(\r\n|\r|\n)+/g," ")};goog.string.canonicalizeNewlines=function(str){return str.replace(/(\r\n|\r|\n)/g,"\n")};goog.string.normalizeWhitespace=function(str){return str.replace(/\xa0|\s/g," ")};
goog.string.normalizeSpaces=function(str){return str.replace(/\xa0|[ \t]+/g," ")};goog.string.collapseBreakingSpaces=function(str){return str.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};goog.string.trim=goog.string.internal.trim;goog.string.trimLeft=function(str){return str.replace(/^[\s\xa0]+/,"")};goog.string.trimRight=function(str){return str.replace(/[\s\xa0]+$/,"")};goog.string.caseInsensitiveCompare=goog.string.internal.caseInsensitiveCompare;
goog.string.numberAwareCompare_=function(str1,str2,tokenizerRegExp){if(str1==str2)return 0;if(!str1)return-1;if(!str2)return 1;for(var tokens1=str1.toLowerCase().match(tokenizerRegExp),tokens2=str2.toLowerCase().match(tokenizerRegExp),count=Math.min(tokens1.length,tokens2.length),i=0;i<count;i++){var a=tokens1[i],b=tokens2[i];if(a!=b){var num1=parseInt(a,10);if(!isNaN(num1)){var num2=parseInt(b,10);if(!isNaN(num2)&&num1-num2)return num1-num2}return a<b?-1:1}}return tokens1.length!=tokens2.length?
tokens1.length-tokens2.length:str1<str2?-1:1};goog.string.intAwareCompare=function(str1,str2){return goog.string.numberAwareCompare_(str1,str2,/\d+|\D+/g)};goog.string.floatAwareCompare=function(str1,str2){return goog.string.numberAwareCompare_(str1,str2,/\d+|\.\d+|\D+/g)};goog.string.numerateCompare=goog.string.floatAwareCompare;goog.string.urlEncode=function(str){return encodeURIComponent(String(str))};goog.string.urlDecode=function(str){return decodeURIComponent(str.replace(/\+/g," "))};
goog.string.newLineToBr=goog.string.internal.newLineToBr;goog.string.htmlEscape=function(str,opt_isLikelyToContainHtmlChars){str=goog.string.internal.htmlEscape(str,opt_isLikelyToContainHtmlChars);goog.string.DETECT_DOUBLE_ESCAPING&&(str=str.replace(goog.string.E_RE_,"&#101;"));return str};goog.string.E_RE_=/e/g;
goog.string.unescapeEntities=function(str){return goog.string.contains(str,"&")?!goog.string.FORCE_NON_DOM_HTML_UNESCAPING&&"document"in goog.global?goog.string.unescapeEntitiesUsingDom_(str):goog.string.unescapePureXmlEntities_(str):str};goog.string.unescapeEntitiesWithDocument=function(str,document){return goog.string.contains(str,"&")?goog.string.unescapeEntitiesUsingDom_(str,document):str};
goog.string.unescapeEntitiesUsingDom_=function(str,opt_document){var seen={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var div=opt_document?opt_document.createElement("div"):goog.global.document.createElement("div");return str.replace(goog.string.HTML_ENTITY_PATTERN_,function(s,entity){var value=seen[s];if(value)return value;if("#"==entity.charAt(0)){var n=Number("0"+entity.substr(1));isNaN(n)||(value=String.fromCharCode(n))}value||(goog.dom.safe.setInnerHtml(div,goog.html.uncheckedconversions.safeHtmlFromStringKnownToSatisfyTypeContract(goog.string.Const.from("Single HTML entity."),
s+" ")),value=div.firstChild.nodeValue.slice(0,-1));return seen[s]=value})};goog.string.unescapePureXmlEntities_=function(str){return str.replace(/&([^;]+);/g,function(s,entity){switch(entity){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==entity.charAt(0)){var n=Number("0"+entity.substr(1));if(!isNaN(n))return String.fromCharCode(n)}return s}})};goog.string.HTML_ENTITY_PATTERN_=/&([^;\s<&]+);?/g;
goog.string.whitespaceEscape=function(str,opt_xml){return goog.string.newLineToBr(str.replace(/  /g," &#160;"),opt_xml)};goog.string.preserveSpaces=function(str){return str.replace(/(^|[\n ]) /g,"$1"+goog.string.Unicode.NBSP)};goog.string.stripQuotes=function(str,quoteChars){for(var length=quoteChars.length,i=0;i<length;i++){var quoteChar=1==length?quoteChars:quoteChars.charAt(i);if(str.charAt(0)==quoteChar&&str.charAt(str.length-1)==quoteChar)return str.substring(1,str.length-1)}return str};
goog.string.truncate=function(str,chars,opt_protectEscapedCharacters){opt_protectEscapedCharacters&&(str=goog.string.unescapeEntities(str));str.length>chars&&(str=str.substring(0,chars-3)+"...");opt_protectEscapedCharacters&&(str=goog.string.htmlEscape(str));return str};
goog.string.truncateMiddle=function(str,chars,opt_protectEscapedCharacters,opt_trailingChars){opt_protectEscapedCharacters&&(str=goog.string.unescapeEntities(str));if(opt_trailingChars&&str.length>chars){opt_trailingChars>chars&&(opt_trailingChars=chars);var endPoint=str.length-opt_trailingChars,startPoint=chars-opt_trailingChars;str=str.substring(0,startPoint)+"..."+str.substring(endPoint)}else if(str.length>chars){var half=Math.floor(chars/2),endPos=str.length-half;half+=chars%2;str=str.substring(0,
half)+"..."+str.substring(endPos)}opt_protectEscapedCharacters&&(str=goog.string.htmlEscape(str));return str};goog.string.specialEscapeChars_={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"};goog.string.jsEscapeCache_={"'":"\\'"};
goog.string.quote=function(s){s=String(s);for(var sb=['"'],i=0;i<s.length;i++){var ch=s.charAt(i),cc=ch.charCodeAt(0);sb[i+1]=goog.string.specialEscapeChars_[ch]||(31<cc&&127>cc?ch:goog.string.escapeChar(ch))}sb.push('"');return sb.join("")};goog.string.escapeString=function(str){for(var sb=[],i=0;i<str.length;i++)sb[i]=goog.string.escapeChar(str.charAt(i));return sb.join("")};
goog.string.escapeChar=function(c){if(c in goog.string.jsEscapeCache_)return goog.string.jsEscapeCache_[c];if(c in goog.string.specialEscapeChars_)return goog.string.jsEscapeCache_[c]=goog.string.specialEscapeChars_[c];var cc=c.charCodeAt(0);if(31<cc&&127>cc)var rv=c;else{if(256>cc){if(rv="\\x",16>cc||256<cc)rv+="0"}else rv="\\u",4096>cc&&(rv+="0");rv+=cc.toString(16).toUpperCase()}return goog.string.jsEscapeCache_[c]=rv};goog.string.contains=goog.string.internal.contains;
goog.string.caseInsensitiveContains=goog.string.internal.caseInsensitiveContains;goog.string.countOf=function(s,ss){return s&&ss?s.split(ss).length-1:0};goog.string.removeAt=function(s,index,stringLength){var resultStr=s;0<=index&&index<s.length&&0<stringLength&&(resultStr=s.substr(0,index)+s.substr(index+stringLength,s.length-index-stringLength));return resultStr};goog.string.remove=function(str,substr){return str.replace(substr,"")};
goog.string.removeAll=function(s,ss){var re=new RegExp(goog.string.regExpEscape(ss),"g");return s.replace(re,"")};goog.string.replaceAll=function(s,ss,replacement){var re=new RegExp(goog.string.regExpEscape(ss),"g");return s.replace(re,replacement.replace(/\$/g,"$$$$"))};goog.string.regExpEscape=function(s){return String(s).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
goog.string.repeat=String.prototype.repeat?function(string,length){return string.repeat(length)}:function(string,length){return Array(length+1).join(string)};goog.string.padNumber=function(num,length,opt_precision){var s=void 0!==opt_precision?num.toFixed(opt_precision):String(num),index=s.indexOf(".");-1==index&&(index=s.length);return goog.string.repeat("0",Math.max(0,length-index))+s};goog.string.makeSafe=function(obj){return null==obj?"":String(obj)};
goog.string.buildString=function(var_args){return Array.prototype.join.call(arguments,"")};goog.string.getRandomString=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^goog.now()).toString(36)};goog.string.compareVersions=goog.string.internal.compareVersions;goog.string.hashCode=function(str){for(var result=0,i=0;i<str.length;++i)result=31*result+str.charCodeAt(i)>>>0;return result};
goog.string.uniqueStringCounter_=2147483648*Math.random()|0;goog.string.createUniqueString=function(){return"goog_"+goog.string.uniqueStringCounter_++};goog.string.toNumber=function(str){var num=Number(str);return 0==num&&goog.string.isEmptyOrWhitespace(str)?NaN:num};goog.string.isLowerCamelCase=function(str){return/^[a-z]+([A-Z][a-z]*)*$/.test(str)};goog.string.isUpperCamelCase=function(str){return/^([A-Z][a-z]*)+$/.test(str)};
goog.string.toCamelCase=function(str){return String(str).replace(/\-([a-z])/g,function(all,match){return match.toUpperCase()})};goog.string.toSelectorCase=function(str){return String(str).replace(/([A-Z])/g,"-$1").toLowerCase()};
goog.string.toTitleCase=function(str,opt_delimiters){var delimiters="string"===typeof opt_delimiters?goog.string.regExpEscape(opt_delimiters):"\\s";delimiters=delimiters?"|["+delimiters+"]+":"";var regexp=new RegExp("(^"+delimiters+")([a-z])","g");return str.replace(regexp,function(all,p1,p2){return p1+p2.toUpperCase()})};goog.string.capitalize=function(str){return String(str.charAt(0)).toUpperCase()+String(str.substr(1)).toLowerCase()};
goog.string.parseInt=function(value){isFinite(value)&&(value=String(value));return"string"===typeof value?/^\s*-?0x/i.test(value)?parseInt(value,16):parseInt(value,10):NaN};goog.string.splitLimit=function(str,separator,limit){for(var parts=str.split(separator),returnVal=[];0<limit&&parts.length;)returnVal.push(parts.shift()),limit--;parts.length&&returnVal.push(parts.join(separator));return returnVal};
goog.string.lastComponent=function(str,separators){if(separators)"string"==typeof separators&&(separators=[separators]);else return str;for(var lastSeparatorIndex=-1,i=0;i<separators.length;i++)if(""!=separators[i]){var currentSeparatorIndex=str.lastIndexOf(separators[i]);currentSeparatorIndex>lastSeparatorIndex&&(lastSeparatorIndex=currentSeparatorIndex)}return-1==lastSeparatorIndex?str:str.slice(lastSeparatorIndex+1)};
goog.string.editDistance=function(a,b){var v0=[],v1=[];if(a==b)return 0;if(!a.length||!b.length)return Math.max(a.length,b.length);for(var i=0;i<b.length+1;i++)v0[i]=i;for(i=0;i<a.length;i++){v1[0]=i+1;for(var j=0;j<b.length;j++){var cost=Number(a[i]!=b[j]);v1[j+1]=Math.min(v1[j]+1,v0[j+1]+1,v0[j]+cost)}for(j=0;j<v0.length;j++)v0[j]=v1[j]}return v1[b.length]};goog.labs.userAgent.platform={};goog.labs.userAgent.platform.isAndroid=function(){return goog.labs.userAgent.util.matchUserAgent("Android")};goog.labs.userAgent.platform.isIpod=function(){return goog.labs.userAgent.util.matchUserAgent("iPod")};goog.labs.userAgent.platform.isIphone=function(){return goog.labs.userAgent.util.matchUserAgent("iPhone")&&!goog.labs.userAgent.util.matchUserAgent("iPod")&&!goog.labs.userAgent.util.matchUserAgent("iPad")};goog.labs.userAgent.platform.isIpad=function(){return goog.labs.userAgent.util.matchUserAgent("iPad")};
goog.labs.userAgent.platform.isIos=function(){return goog.labs.userAgent.platform.isIphone()||goog.labs.userAgent.platform.isIpad()||goog.labs.userAgent.platform.isIpod()};goog.labs.userAgent.platform.isMacintosh=function(){return goog.labs.userAgent.util.matchUserAgent("Macintosh")};goog.labs.userAgent.platform.isLinux=function(){return goog.labs.userAgent.util.matchUserAgent("Linux")};goog.labs.userAgent.platform.isWindows=function(){return goog.labs.userAgent.util.matchUserAgent("Windows")};
goog.labs.userAgent.platform.isChromeOS=function(){return goog.labs.userAgent.util.matchUserAgent("CrOS")};goog.labs.userAgent.platform.isChromecast=function(){return goog.labs.userAgent.util.matchUserAgent("CrKey")};goog.labs.userAgent.platform.isKaiOS=function(){return goog.labs.userAgent.util.matchUserAgentIgnoreCase("KaiOS")};goog.labs.userAgent.platform.isGo2Phone=function(){return goog.labs.userAgent.util.matchUserAgentIgnoreCase("GAFP")};
goog.labs.userAgent.platform.getVersion=function(){var userAgentString=goog.labs.userAgent.util.getUserAgent(),version="";if(goog.labs.userAgent.platform.isWindows()){var re=/Windows (?:NT|Phone) ([0-9.]+)/;var match=re.exec(userAgentString);version=match?match[1]:"0.0"}else goog.labs.userAgent.platform.isIos()?(re=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,version=(match=re.exec(userAgentString))&&match[1].replace(/_/g,".")):goog.labs.userAgent.platform.isMacintosh()?(re=/Mac OS X ([0-9_.]+)/,version=
(match=re.exec(userAgentString))?match[1].replace(/_/g,"."):"10"):goog.labs.userAgent.platform.isKaiOS()?(re=/(?:KaiOS)\/(\S+)/i,version=(match=re.exec(userAgentString))&&match[1]):goog.labs.userAgent.platform.isAndroid()?(re=/Android\s+([^\);]+)(\)|;)/,version=(match=re.exec(userAgentString))&&match[1]):goog.labs.userAgent.platform.isChromeOS()&&(re=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,version=(match=re.exec(userAgentString))&&match[1]);return version||""};
goog.labs.userAgent.platform.isVersionOrHigher=function(version){return 0<=goog.string.compareVersions(goog.labs.userAgent.platform.getVersion(),version)};goog.labs.userAgent.engine={};goog.labs.userAgent.engine.isPresto=function(){return goog.labs.userAgent.util.matchUserAgent("Presto")};goog.labs.userAgent.engine.isTrident=function(){return goog.labs.userAgent.util.matchUserAgent("Trident")||goog.labs.userAgent.util.matchUserAgent("MSIE")};goog.labs.userAgent.engine.isEdge=function(){return goog.labs.userAgent.util.matchUserAgent("Edge")};
goog.labs.userAgent.engine.isWebKit=function(){return goog.labs.userAgent.util.matchUserAgentIgnoreCase("WebKit")&&!goog.labs.userAgent.engine.isEdge()};goog.labs.userAgent.engine.isGecko=function(){return goog.labs.userAgent.util.matchUserAgent("Gecko")&&!goog.labs.userAgent.engine.isWebKit()&&!goog.labs.userAgent.engine.isTrident()&&!goog.labs.userAgent.engine.isEdge()};
goog.labs.userAgent.engine.getVersion=function(){var userAgentString=goog.labs.userAgent.util.getUserAgent();if(userAgentString){var tuples=goog.labs.userAgent.util.extractVersionTuples(userAgentString),engineTuple=goog.labs.userAgent.engine.getEngineTuple_(tuples);if(engineTuple)return"Gecko"==engineTuple[0]?goog.labs.userAgent.engine.getVersionForKey_(tuples,"Firefox"):engineTuple[1];var browserTuple=tuples[0],info;if(browserTuple&&(info=browserTuple[2])){var match=/Trident\/([^\s;]+)/.exec(info);
if(match)return match[1]}}return""};goog.labs.userAgent.engine.getEngineTuple_=function(tuples){if(!goog.labs.userAgent.engine.isEdge())return tuples[1];for(var i=0;i<tuples.length;i++){var tuple=tuples[i];if("Edge"==tuple[0])return tuple}};goog.labs.userAgent.engine.isVersionOrHigher=function(version){return 0<=goog.string.compareVersions(goog.labs.userAgent.engine.getVersion(),version)};
goog.labs.userAgent.engine.getVersionForKey_=function(tuples,key){var pair=goog.array.find(tuples,function(pair){return key==pair[0]});return pair&&pair[1]||""};goog.reflect={};goog.reflect.object=function(type,object){return object};goog.reflect.objectProperty=function(prop){return prop};goog.reflect.sinkValue=function(x){goog.reflect.sinkValue[" "](x);return x};goog.reflect.sinkValue[" "]=goog.nullFunction;goog.reflect.canAccessProperty=function(obj,prop){try{return goog.reflect.sinkValue(obj[prop]),!0}catch(e){}return!1};
goog.reflect.cache=function(cacheObj,key,valueFn,opt_keyFn){var storedKey=opt_keyFn?opt_keyFn(key):key;return Object.prototype.hasOwnProperty.call(cacheObj,storedKey)?cacheObj[storedKey]:cacheObj[storedKey]=valueFn(key)};goog.userAgent={};goog.userAgent.ASSUME_IE=!1;goog.userAgent.ASSUME_EDGE=!1;goog.userAgent.ASSUME_GECKO=!1;goog.userAgent.ASSUME_WEBKIT=!1;goog.userAgent.ASSUME_MOBILE_WEBKIT=!1;goog.userAgent.ASSUME_OPERA=!1;goog.userAgent.ASSUME_ANY_VERSION=!1;goog.userAgent.BROWSER_KNOWN_=goog.userAgent.ASSUME_IE||goog.userAgent.ASSUME_EDGE||goog.userAgent.ASSUME_GECKO||goog.userAgent.ASSUME_MOBILE_WEBKIT||goog.userAgent.ASSUME_WEBKIT||goog.userAgent.ASSUME_OPERA;goog.userAgent.getUserAgentString=function(){return goog.labs.userAgent.util.getUserAgent()};
goog.userAgent.getNavigatorTyped=function(){return goog.global.navigator||null};goog.userAgent.getNavigator=function(){return goog.userAgent.getNavigatorTyped()};goog.userAgent.OPERA=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_OPERA:goog.labs.userAgent.browser.isOpera();goog.userAgent.IE=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_IE:goog.labs.userAgent.browser.isIE();goog.userAgent.EDGE=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_EDGE:goog.labs.userAgent.engine.isEdge();
goog.userAgent.EDGE_OR_IE=goog.userAgent.EDGE||goog.userAgent.IE;goog.userAgent.GECKO=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_GECKO:goog.labs.userAgent.engine.isGecko();goog.userAgent.WEBKIT=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_WEBKIT||goog.userAgent.ASSUME_MOBILE_WEBKIT:goog.labs.userAgent.engine.isWebKit();goog.userAgent.isMobile_=function(){return goog.userAgent.WEBKIT&&goog.labs.userAgent.util.matchUserAgent("Mobile")};
goog.userAgent.MOBILE=goog.userAgent.ASSUME_MOBILE_WEBKIT||goog.userAgent.isMobile_();goog.userAgent.SAFARI=goog.userAgent.WEBKIT;goog.userAgent.determinePlatform_=function(){var navigator=goog.userAgent.getNavigatorTyped();return navigator&&navigator.platform||""};goog.userAgent.PLATFORM=goog.userAgent.determinePlatform_();goog.userAgent.ASSUME_MAC=!1;goog.userAgent.ASSUME_WINDOWS=!1;goog.userAgent.ASSUME_LINUX=!1;goog.userAgent.ASSUME_X11=!1;goog.userAgent.ASSUME_ANDROID=!1;
goog.userAgent.ASSUME_IPHONE=!1;goog.userAgent.ASSUME_IPAD=!1;goog.userAgent.ASSUME_IPOD=!1;goog.userAgent.ASSUME_KAIOS=!1;goog.userAgent.ASSUME_GO2PHONE=!1;goog.userAgent.PLATFORM_KNOWN_=goog.userAgent.ASSUME_MAC||goog.userAgent.ASSUME_WINDOWS||goog.userAgent.ASSUME_LINUX||goog.userAgent.ASSUME_X11||goog.userAgent.ASSUME_ANDROID||goog.userAgent.ASSUME_IPHONE||goog.userAgent.ASSUME_IPAD||goog.userAgent.ASSUME_IPOD;goog.userAgent.MAC=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_MAC:goog.labs.userAgent.platform.isMacintosh();
goog.userAgent.WINDOWS=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_WINDOWS:goog.labs.userAgent.platform.isWindows();goog.userAgent.isLegacyLinux_=function(){return goog.labs.userAgent.platform.isLinux()||goog.labs.userAgent.platform.isChromeOS()};goog.userAgent.LINUX=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_LINUX:goog.userAgent.isLegacyLinux_();
goog.userAgent.isX11_=function(){var navigator=goog.userAgent.getNavigatorTyped();return!!navigator&&goog.string.contains(navigator.appVersion||"","X11")};goog.userAgent.X11=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_X11:goog.userAgent.isX11_();goog.userAgent.ANDROID=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_ANDROID:goog.labs.userAgent.platform.isAndroid();goog.userAgent.IPHONE=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_IPHONE:goog.labs.userAgent.platform.isIphone();
goog.userAgent.IPAD=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_IPAD:goog.labs.userAgent.platform.isIpad();goog.userAgent.IPOD=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_IPOD:goog.labs.userAgent.platform.isIpod();goog.userAgent.IOS=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_IPHONE||goog.userAgent.ASSUME_IPAD||goog.userAgent.ASSUME_IPOD:goog.labs.userAgent.platform.isIos();goog.userAgent.KAIOS=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_KAIOS:goog.labs.userAgent.platform.isKaiOS();
goog.userAgent.GO2PHONE=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_GO2PHONE:goog.labs.userAgent.platform.isGo2Phone();goog.userAgent.determineVersion_=function(){var version="",arr=goog.userAgent.getVersionRegexResult_();arr&&(version=arr?arr[1]:"");if(goog.userAgent.IE){var docMode=goog.userAgent.getDocumentMode_();if(null!=docMode&&docMode>parseFloat(version))return String(docMode)}return version};
goog.userAgent.getVersionRegexResult_=function(){var userAgent=goog.userAgent.getUserAgentString();if(goog.userAgent.GECKO)return/rv:([^\);]+)(\)|;)/.exec(userAgent);if(goog.userAgent.EDGE)return/Edge\/([\d\.]+)/.exec(userAgent);if(goog.userAgent.IE)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(userAgent);if(goog.userAgent.WEBKIT)return/WebKit\/(\S+)/.exec(userAgent);if(goog.userAgent.OPERA)return/(?:Version)[ \/]?(\S+)/.exec(userAgent)};
goog.userAgent.getDocumentMode_=function(){var doc=goog.global.document;return doc?doc.documentMode:void 0};goog.userAgent.VERSION=goog.userAgent.determineVersion_();goog.userAgent.compare=function(v1,v2){return goog.string.compareVersions(v1,v2)};goog.userAgent.isVersionOrHigherCache_={};
goog.userAgent.isVersionOrHigher=function(version){return goog.userAgent.ASSUME_ANY_VERSION||goog.reflect.cache(goog.userAgent.isVersionOrHigherCache_,version,function(){return 0<=goog.string.compareVersions(goog.userAgent.VERSION,version)})};goog.userAgent.isVersion=goog.userAgent.isVersionOrHigher;goog.userAgent.isDocumentModeOrHigher=function(documentMode){return Number(goog.userAgent.DOCUMENT_MODE)>=documentMode};goog.userAgent.isDocumentMode=goog.userAgent.isDocumentModeOrHigher;var JSCompiler_inline_result$jscomp$22;
var doc$jscomp$inline_25=goog.global.document;JSCompiler_inline_result$jscomp$22=doc$jscomp$inline_25&&goog.userAgent.IE?goog.userAgent.getDocumentMode_():void 0;goog.userAgent.DOCUMENT_MODE=JSCompiler_inline_result$jscomp$22;goog.userAgent.product={};goog.userAgent.product.ASSUME_FIREFOX=!1;goog.userAgent.product.ASSUME_IPHONE=!1;goog.userAgent.product.ASSUME_IPAD=!1;goog.userAgent.product.ASSUME_ANDROID=!1;goog.userAgent.product.ASSUME_CHROME=!1;goog.userAgent.product.ASSUME_SAFARI=!1;
goog.userAgent.product.PRODUCT_KNOWN_=goog.userAgent.ASSUME_IE||goog.userAgent.ASSUME_EDGE||goog.userAgent.ASSUME_OPERA||goog.userAgent.product.ASSUME_FIREFOX||goog.userAgent.product.ASSUME_IPHONE||goog.userAgent.product.ASSUME_IPAD||goog.userAgent.product.ASSUME_ANDROID||goog.userAgent.product.ASSUME_CHROME||goog.userAgent.product.ASSUME_SAFARI;goog.userAgent.product.OPERA=goog.userAgent.OPERA;goog.userAgent.product.IE=goog.userAgent.IE;goog.userAgent.product.EDGE=goog.userAgent.EDGE;
goog.userAgent.product.FIREFOX=goog.userAgent.product.PRODUCT_KNOWN_?goog.userAgent.product.ASSUME_FIREFOX:goog.labs.userAgent.browser.isFirefox();goog.userAgent.product.isIphoneOrIpod_=function(){return goog.labs.userAgent.platform.isIphone()||goog.labs.userAgent.platform.isIpod()};goog.userAgent.product.IPHONE=goog.userAgent.product.PRODUCT_KNOWN_?goog.userAgent.product.ASSUME_IPHONE:goog.userAgent.product.isIphoneOrIpod_();
goog.userAgent.product.IPAD=goog.userAgent.product.PRODUCT_KNOWN_?goog.userAgent.product.ASSUME_IPAD:goog.labs.userAgent.platform.isIpad();goog.userAgent.product.ANDROID=goog.userAgent.product.PRODUCT_KNOWN_?goog.userAgent.product.ASSUME_ANDROID:goog.labs.userAgent.browser.isAndroidBrowser();goog.userAgent.product.CHROME=goog.userAgent.product.PRODUCT_KNOWN_?goog.userAgent.product.ASSUME_CHROME:goog.labs.userAgent.browser.isChrome();
goog.userAgent.product.isSafariDesktop_=function(){return goog.labs.userAgent.browser.isSafari()&&!goog.labs.userAgent.platform.isIos()};goog.userAgent.product.SAFARI=goog.userAgent.product.PRODUCT_KNOWN_?goog.userAgent.product.ASSUME_SAFARI:goog.userAgent.product.isSafariDesktop_();goog.crypt.base64={};goog.crypt.base64.DEFAULT_ALPHABET_COMMON_="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";goog.crypt.base64.ENCODED_VALS=goog.crypt.base64.DEFAULT_ALPHABET_COMMON_+"+/=";goog.crypt.base64.ENCODED_VALS_WEBSAFE=goog.crypt.base64.DEFAULT_ALPHABET_COMMON_+"-_.";goog.crypt.base64.Alphabet={DEFAULT:0,NO_PADDING:1,WEBSAFE:2,WEBSAFE_DOT_PADDING:3,WEBSAFE_NO_PADDING:4};goog.crypt.base64.paddingChars_="=.";
goog.crypt.base64.isPadding_=function(char){return goog.string.contains(goog.crypt.base64.paddingChars_,char)};goog.crypt.base64.byteToCharMaps_={};goog.crypt.base64.charToByteMap_=null;goog.crypt.base64.ASSUME_NATIVE_SUPPORT_=goog.userAgent.GECKO||goog.userAgent.WEBKIT&&!goog.userAgent.product.SAFARI||goog.userAgent.OPERA;goog.crypt.base64.HAS_NATIVE_ENCODE_=goog.crypt.base64.ASSUME_NATIVE_SUPPORT_||"function"==typeof goog.global.btoa;
goog.crypt.base64.HAS_NATIVE_DECODE_=goog.crypt.base64.ASSUME_NATIVE_SUPPORT_||!goog.userAgent.product.SAFARI&&!goog.userAgent.IE&&"function"==typeof goog.global.atob;
goog.crypt.base64.encodeByteArray=function(input,alphabet){goog.asserts.assert(goog.isArrayLike(input),"encodeByteArray takes an array as a parameter");void 0===alphabet&&(alphabet=goog.crypt.base64.Alphabet.DEFAULT);goog.crypt.base64.init_();for(var byteToCharMap=goog.crypt.base64.byteToCharMaps_[alphabet],output=[],i=0;i<input.length;i+=3){var byte1=input[i],haveByte2=i+1<input.length,byte2=haveByte2?input[i+1]:0,haveByte3=i+2<input.length,byte3=haveByte3?input[i+2]:0,outByte1=byte1>>2,outByte2=
(byte1&3)<<4|byte2>>4,outByte3=(byte2&15)<<2|byte3>>6,outByte4=byte3&63;haveByte3||(outByte4=64,haveByte2||(outByte3=64));output.push(byteToCharMap[outByte1],byteToCharMap[outByte2],byteToCharMap[outByte3]||"",byteToCharMap[outByte4]||"")}return output.join("")};goog.crypt.base64.encodeString=function(input,alphabet){return goog.crypt.base64.HAS_NATIVE_ENCODE_&&!alphabet?goog.global.btoa(input):goog.crypt.base64.encodeByteArray(goog.crypt.stringToByteArray(input),alphabet)};
goog.crypt.base64.decodeString=function(input,useCustomDecoder){function pushByte(b){output+=String.fromCharCode(b)}if(goog.crypt.base64.HAS_NATIVE_DECODE_&&!useCustomDecoder)return goog.global.atob(input);var output="";goog.crypt.base64.decodeStringInternal_(input,pushByte);return output};goog.crypt.base64.decodeStringToByteArray=function(input){function pushByte(b){output.push(b)}var output=[];goog.crypt.base64.decodeStringInternal_(input,pushByte);return output};
goog.crypt.base64.decodeStringToUint8Array=function(input){function pushByte(b){output[outLen++]=b}goog.asserts.assert(!goog.userAgent.IE||goog.userAgent.isVersionOrHigher("10"),"Browser does not support typed arrays");var len=input.length,approxByteLength=3*len/4;approxByteLength%3?approxByteLength=Math.floor(approxByteLength):goog.crypt.base64.isPadding_(input[len-1])&&(approxByteLength=goog.crypt.base64.isPadding_(input[len-2])?approxByteLength-2:approxByteLength-1);var output=new Uint8Array(approxByteLength),
outLen=0;goog.crypt.base64.decodeStringInternal_(input,pushByte);return output.subarray(0,outLen)};
goog.crypt.base64.decodeStringInternal_=function(input,pushByte){function getByte(default_val){for(;nextCharIndex<input.length;){var ch=input.charAt(nextCharIndex++),b=goog.crypt.base64.charToByteMap_[ch];if(null!=b)return b;if(!goog.string.isEmptyOrWhitespace(ch))throw Error("Unknown base64 encoding at char: "+ch);}return default_val}goog.crypt.base64.init_();for(var nextCharIndex=0;;){var byte1=getByte(-1),byte2=getByte(0),byte3=getByte(64),byte4=getByte(64);if(64===byte4&&-1===byte1)break;var outByte1=
byte1<<2|byte2>>4;pushByte(outByte1);if(64!=byte3){var outByte2=byte2<<4&240|byte3>>2;pushByte(outByte2);if(64!=byte4){var outByte3=byte3<<6&192|byte4;pushByte(outByte3)}}}};
goog.crypt.base64.init_=function(){if(!goog.crypt.base64.charToByteMap_){goog.crypt.base64.charToByteMap_={};for(var commonChars=goog.crypt.base64.DEFAULT_ALPHABET_COMMON_.split(""),specialChars=["+/=","+/","-_=","-_.","-_"],i=0;5>i;i++){var chars=commonChars.concat(specialChars[i].split(""));goog.crypt.base64.byteToCharMaps_[i]=chars;for(var j=0;j<chars.length;j++){var char=chars[j],existingByte=goog.crypt.base64.charToByteMap_[char];void 0===existingByte?goog.crypt.base64.charToByteMap_[char]=j:
goog.asserts.assert(existingByte===j)}}}};var module$exports$tink$Aead=function(){};module$exports$tink$Aead.prototype.encrypt=function(){};module$exports$tink$Aead.prototype.decrypt=function(){};var module$exports$tink$exception$SecurityException=function(opt_msg){goog.debug.Error.call(this,opt_msg)};$jscomp.inherits(module$exports$tink$exception$SecurityException,goog.debug.Error);var jspb={BinaryConstants:{},ConstBinaryMessage:function(){},BinaryMessage:function(){}};jspb.BinaryConstants.FieldType={INVALID:-1,DOUBLE:1,FLOAT:2,INT64:3,UINT64:4,INT32:5,FIXED64:6,FIXED32:7,BOOL:8,STRING:9,GROUP:10,MESSAGE:11,BYTES:12,UINT32:13,ENUM:14,SFIXED32:15,SFIXED64:16,SINT32:17,SINT64:18,FHASH64:30,VHASH64:31};jspb.BinaryConstants.WireType={INVALID:-1,VARINT:0,FIXED64:1,DELIMITED:2,START_GROUP:3,END_GROUP:4,FIXED32:5};
jspb.BinaryConstants.FieldTypeToWireType=function(fieldType){var fieldTypes=jspb.BinaryConstants.FieldType,wireTypes=jspb.BinaryConstants.WireType;switch(fieldType){case fieldTypes.INT32:case fieldTypes.INT64:case fieldTypes.UINT32:case fieldTypes.UINT64:case fieldTypes.SINT32:case fieldTypes.SINT64:case fieldTypes.BOOL:case fieldTypes.ENUM:case fieldTypes.VHASH64:return wireTypes.VARINT;case fieldTypes.DOUBLE:case fieldTypes.FIXED64:case fieldTypes.SFIXED64:case fieldTypes.FHASH64:return wireTypes.FIXED64;
case fieldTypes.STRING:case fieldTypes.MESSAGE:case fieldTypes.BYTES:return wireTypes.DELIMITED;case fieldTypes.FLOAT:case fieldTypes.FIXED32:case fieldTypes.SFIXED32:return wireTypes.FIXED32;default:return wireTypes.INVALID}};jspb.BinaryConstants.INVALID_FIELD_NUMBER=-1;jspb.BinaryConstants.FLOAT32_EPS=1.401298464324817E-45;jspb.BinaryConstants.FLOAT32_MIN=1.1754943508222875E-38;jspb.BinaryConstants.FLOAT32_MAX=3.4028234663852886E38;jspb.BinaryConstants.FLOAT64_EPS=4.9E-324;
jspb.BinaryConstants.FLOAT64_MIN=2.2250738585072014E-308;jspb.BinaryConstants.FLOAT64_MAX=1.7976931348623157E308;jspb.BinaryConstants.TWO_TO_20=1048576;jspb.BinaryConstants.TWO_TO_23=8388608;jspb.BinaryConstants.TWO_TO_31=2147483648;jspb.BinaryConstants.TWO_TO_32=4294967296;jspb.BinaryConstants.TWO_TO_52=4503599627370496;jspb.BinaryConstants.TWO_TO_63=0x7fffffffffffffff;jspb.BinaryConstants.TWO_TO_64=1.8446744073709552E19;jspb.BinaryConstants.ZERO_HASH="\x00\x00\x00\x00\x00\x00\x00\x00";jspb.utils={};jspb.utils.split64Low=0;jspb.utils.split64High=0;jspb.utils.splitUint64=function(value){var lowBits=value>>>0,highBits=Math.floor((value-lowBits)/jspb.BinaryConstants.TWO_TO_32)>>>0;jspb.utils.split64Low=lowBits;jspb.utils.split64High=highBits};
jspb.utils.splitInt64=function(value){var sign=0>value;value=Math.abs(value);var lowBits=value>>>0,highBits=Math.floor((value-lowBits)/jspb.BinaryConstants.TWO_TO_32);highBits>>>=0;sign&&(highBits=~highBits>>>0,lowBits=~lowBits>>>0,lowBits+=1,4294967295<lowBits&&(lowBits=0,highBits++,4294967295<highBits&&(highBits=0)));jspb.utils.split64Low=lowBits;jspb.utils.split64High=highBits};
jspb.utils.splitZigzag64=function(value){var sign=0>value;value=2*Math.abs(value);jspb.utils.splitUint64(value);var lowBits=jspb.utils.split64Low,highBits=jspb.utils.split64High;sign&&(0==lowBits?0==highBits?highBits=lowBits=4294967295:(highBits--,lowBits=4294967295):lowBits--);jspb.utils.split64Low=lowBits;jspb.utils.split64High=highBits};
jspb.utils.splitFloat32=function(value){var sign=0>value?1:0;value=sign?-value:value;if(0===value)0<1/value?(jspb.utils.split64High=0,jspb.utils.split64Low=0):(jspb.utils.split64High=0,jspb.utils.split64Low=2147483648);else if(isNaN(value))jspb.utils.split64High=0,jspb.utils.split64Low=2147483647;else if(value>jspb.BinaryConstants.FLOAT32_MAX)jspb.utils.split64High=0,jspb.utils.split64Low=(sign<<31|2139095040)>>>0;else if(value<jspb.BinaryConstants.FLOAT32_MIN){var mant=Math.round(value/Math.pow(2,
-149));jspb.utils.split64High=0;jspb.utils.split64Low=
